WITH checklist_templates AS (
  SELECT * FROM (
    VALUES
      ('CHECKLIST ABERTURA — POKE', 'abertura', 'Setor: Cozinha | Responsável: Preparador Poke | Horário: Antes das 11:00'),
      ('CHECKLIST ABERTURA — BOWL', 'abertura', 'Setor: Cozinha | Responsável: Preparador Bowl | Horário: Antes das 11:00'),
      ('CHECKLIST ABERTURA — WRAP', 'abertura', 'Setor: Cozinha | Responsável: Preparador Wrap | Horário: Não informado'),
      ('CHECKLIST ABERTURA — SALADA', 'abertura', 'Setor: Cozinha | Responsável: Preparador Salada | Horário: Não informado'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 'abertura', 'Setor: Cozinha | Responsável: Preparador Proteína | Horário: Não informado'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 'abertura', 'Setor: Cocção | Responsável: Chapeiro/Fritador | Horário: 8:00-9:00'),
      ('CHECKLIST ABERTURA — DELIVERY', 'abertura', 'Setor: Salão | Responsável: Atendente Delivery | Horário: Não informado'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 'abertura', 'Setor: Salão | Responsável: Barista | Horário: Não informado'),
      ('CHECKLIST ABERTURA — LAVAGEM', 'abertura', 'Setor: Apoio | Responsável: Auxiliar de Lavagem | Horário: 8:00'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 'abertura', 'Setor: Apoio | Responsável: Auxiliar de Limpeza | Horário: 8:00-11:00'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 'abertura', 'Setor: Gerência | Responsável: Coordenador | Horário: 8:00-11:00')
  ) AS t(name, checklist_type, description)
),
inserted_checklists AS (
  INSERT INTO public.checklists (network_id, name, checklist_type, is_active)
  SELECT n.id, t.name, t.checklist_type::checklist_type, true
  FROM public.networks n
  CROSS JOIN checklist_templates t
  RETURNING id, name, network_id
),
checklist_items AS (
  SELECT * FROM (
    VALUES
      ('CHECKLIST ABERTURA — POKE', 1, 'Chegar com uniforme completo e limpo'),
      ('CHECKLIST ABERTURA — POKE', 2, 'Guardar objetos pessoais'),
      ('CHECKLIST ABERTURA — POKE', 3, 'Retirar adornos (relógio, anéis, pulseiras)'),
      ('CHECKLIST ABERTURA — POKE', 4, 'Colocar touca cobrindo cabelo e orelhas'),
      ('CHECKLIST ABERTURA — POKE', 5, 'Higienizar as mãos'),
      ('CHECKLIST ABERTURA — POKE', 6, 'Abastecer papeleira e saboneteira do setor'),
      ('CHECKLIST ABERTURA — POKE', 7, 'Montar lixeira do setor'),
      ('CHECKLIST ABERTURA — POKE', 8, 'Limpar piso da área Poke'),
      ('CHECKLIST ABERTURA — POKE', 9, 'Limpar superfícies de inox e telas KDS'),
      ('CHECKLIST ABERTURA — POKE', 10, 'Verificar funcionamento de refrigeradores'),
      ('CHECKLIST ABERTURA — POKE', 11, 'Verificar ingrediente: Cebola roxa'),
      ('CHECKLIST ABERTURA — POKE', 12, 'Verificar ingrediente: Quinoa'),
      ('CHECKLIST ABERTURA — POKE', 13, 'Verificar ingrediente: Mix de folhas'),
      ('CHECKLIST ABERTURA — POKE', 14, 'Verificar ingrediente: Arroz japonês'),
      ('CHECKLIST ABERTURA — POKE', 15, 'Verificar ingrediente: Pepino laminado'),
      ('CHECKLIST ABERTURA — POKE', 16, 'Verificar ingrediente: Cebolinha'),
      ('CHECKLIST ABERTURA — POKE', 17, 'Verificar ingrediente: Edamame'),
      ('CHECKLIST ABERTURA — POKE', 18, 'Verificar ingrediente: Abacate'),
      ('CHECKLIST ABERTURA — POKE', 19, 'Verificar ingrediente: Manga'),
      ('CHECKLIST ABERTURA — POKE', 20, 'Verificar ingrediente: Sunomono'),
      ('CHECKLIST ABERTURA — POKE', 21, 'Verificar ingrediente: Pepino palito'),
      ('CHECKLIST ABERTURA — POKE', 22, 'Verificar ingrediente: Cenoura palito'),
      ('CHECKLIST ABERTURA — POKE', 23, 'Verificar ingrediente: Shimeji'),
      ('CHECKLIST ABERTURA — POKE', 24, 'Verificar ingrediente: Salmão'),
      ('CHECKLIST ABERTURA — POKE', 25, 'Verificar ingrediente: Atum'),
      ('CHECKLIST ABERTURA — POKE', 26, 'Verificar complemento: Bear Flakes'),
      ('CHECKLIST ABERTURA — POKE', 27, 'Verificar complemento: Nori'),
      ('CHECKLIST ABERTURA — POKE', 28, 'Verificar complemento: Farofa vegana'),
      ('CHECKLIST ABERTURA — POKE', 29, 'Verificar complemento: Gergelim torrado'),
      ('CHECKLIST ABERTURA — POKE', 30, 'Verificar molho: Molho Black Beer'),
      ('CHECKLIST ABERTURA — POKE', 31, 'Verificar molho: Molho Cítrico'),
      ('CHECKLIST ABERTURA — POKE', 32, 'Verificar molho: Molho Cítrico Vegano'),
      ('CHECKLIST ABERTURA — POKE', 33, 'Verificar molho: Molho Cenoura'),
      ('CHECKLIST ABERTURA — POKE', 34, 'Verificar molho: Molho Togarashi'),
      ('CHECKLIST ABERTURA — POKE', 35, 'Verificar molho: Azeite de trufas'),
      ('CHECKLIST ABERTURA — POKE', 36, 'Conferir etiquetas de validade de todos os insumos'),
      ('CHECKLIST ABERTURA — POKE', 37, 'Realizar requisição de itens faltantes'),
      ('CHECKLIST ABERTURA — POKE', 38, 'Organizar insumos nas cubas/GNs'),
      ('CHECKLIST ABERTURA — POKE', 39, 'Informar coordenador sobre produtos vencidos'),
      ('CHECKLIST ABERTURA — BOWL', 1, 'Chegar com uniforme completo e limpo'),
      ('CHECKLIST ABERTURA — BOWL', 2, 'Higienização pessoal completa'),
      ('CHECKLIST ABERTURA — BOWL', 3, 'Abastecer borrifadores do setor'),
      ('CHECKLIST ABERTURA — BOWL', 4, 'Montar lixeira específica'),
      ('CHECKLIST ABERTURA — BOWL', 5, 'Limpar piso da área Bowl'),
      ('CHECKLIST ABERTURA — BOWL', 6, 'Limpar superfícies de trabalho'),
      ('CHECKLIST ABERTURA — BOWL', 7, 'Verificar temperatura de mantenedores'),
      ('CHECKLIST ABERTURA — BOWL', 8, 'Verificar base: Mix arroz 7 grãos com cogumelo'),
      ('CHECKLIST ABERTURA — BOWL', 9, 'Verificar base: Mix arroz 7 grãos'),
      ('CHECKLIST ABERTURA — BOWL', 10, 'Verificar base: Arroz de brócolis'),
      ('CHECKLIST ABERTURA — BOWL', 11, 'Verificar base: Feijão carioca'),
      ('CHECKLIST ABERTURA — BOWL', 12, 'Verificar base: Feijão fradinho'),
      ('CHECKLIST ABERTURA — BOWL', 13, 'Verificar base: Purê de abóbora'),
      ('CHECKLIST ABERTURA — BOWL', 14, 'Verificar vegetal: Vinagrete'),
      ('CHECKLIST ABERTURA — BOWL', 15, 'Verificar vegetal: Brócolis'),
      ('CHECKLIST ABERTURA — BOWL', 16, 'Verificar vegetal: Couve flor'),
      ('CHECKLIST ABERTURA — BOWL', 17, 'Verificar vegetal: Batata doce'),
      ('CHECKLIST ABERTURA — BOWL', 18, 'Verificar vegetal: Abóbora'),
      ('CHECKLIST ABERTURA — BOWL', 19, 'Verificar vegetal: Abobrinha'),
      ('CHECKLIST ABERTURA — BOWL', 20, 'Verificar vegetal: Tomate cereja e milho'),
      ('CHECKLIST ABERTURA — BOWL', 21, 'Verificar vegetal: Couve'),
      ('CHECKLIST ABERTURA — BOWL', 22, 'Verificar vegetal: Rúcula'),
      ('CHECKLIST ABERTURA — BOWL', 23, 'Verificar creme/queijo: Creme de milho'),
      ('CHECKLIST ABERTURA — BOWL', 24, 'Verificar creme/queijo: Creme de queijo'),
      ('CHECKLIST ABERTURA — BOWL', 25, 'Verificar creme/queijo: Queijo coalho'),
      ('CHECKLIST ABERTURA — BOWL', 26, 'Verificar complemento: Bacon salgado'),
      ('CHECKLIST ABERTURA — BOWL', 27, 'Verificar complemento: Farofa de pão'),
      ('CHECKLIST ABERTURA — BOWL', 28, 'Verificar complemento: Farofa de banana'),
      ('CHECKLIST ABERTURA — BOWL', 29, 'Verificar complemento: Gergelim torrado'),
      ('CHECKLIST ABERTURA — BOWL', 30, 'Verificar complemento: Cebola crocante'),
      ('CHECKLIST ABERTURA — BOWL', 31, 'Verificar proteína: Carne da vovó'),
      ('CHECKLIST ABERTURA — BOWL', 32, 'Verificar proteína: Picadinho vegano'),
      ('CHECKLIST ABERTURA — BOWL', 33, 'Verificar proteína: Carne picadinho'),
      ('CHECKLIST ABERTURA — BOWL', 34, 'Verificar proteína: Salmão grelhado'),
      ('CHECKLIST ABERTURA — BOWL', 35, 'Verificar proteína: Frango grelhado'),
      ('CHECKLIST ABERTURA — BOWL', 36, 'Verificar molho: Molho Teriyaki'),
      ('CHECKLIST ABERTURA — BOWL', 37, 'Verificar molho: Molho da Vovó'),
      ('CHECKLIST ABERTURA — BOWL', 38, 'Verificar molho: Molho Cítrico'),
      ('CHECKLIST ABERTURA — BOWL', 39, 'Verificar molho: Molho Pesto'),
      ('CHECKLIST ABERTURA — BOWL', 40, 'Verificar molho: Molho Picadinho Vegano'),
      ('CHECKLIST ABERTURA — BOWL', 41, 'Item de inverno (se aplicável): Caldo de mandioquinha'),
      ('CHECKLIST ABERTURA — BOWL', 42, 'Item de inverno (se aplicável): Canja'),
      ('CHECKLIST ABERTURA — BOWL', 43, 'Item de inverno (se aplicável): Quinoa crocante'),
      ('CHECKLIST ABERTURA — BOWL', 44, 'Item de inverno (se aplicável): Castanha caramelizada'),
      ('CHECKLIST ABERTURA — BOWL', 45, 'Conferir validades'),
      ('CHECKLIST ABERTURA — BOWL', 46, 'Solicitar reposição se necessário'),
      ('CHECKLIST ABERTURA — WRAP', 1, 'Uniforme e higiene pessoal OK'),
      ('CHECKLIST ABERTURA — WRAP', 2, 'Área limpa e organizada'),
      ('CHECKLIST ABERTURA — WRAP', 3, 'Equipamentos verificados'),
      ('CHECKLIST ABERTURA — WRAP', 4, 'Verificar vegetal: Picles de repolho'),
      ('CHECKLIST ABERTURA — WRAP', 5, 'Verificar vegetal: Picles de cenoura'),
      ('CHECKLIST ABERTURA — WRAP', 6, 'Verificar vegetal: Cebolinha'),
      ('CHECKLIST ABERTURA — WRAP', 7, 'Verificar vegetal: Alface romana'),
      ('CHECKLIST ABERTURA — WRAP', 8, 'Verificar vegetal: Alface americana'),
      ('CHECKLIST ABERTURA — WRAP', 9, 'Verificar vegetal: Alface americana com roxa'),
      ('CHECKLIST ABERTURA — WRAP', 10, 'Verificar vegetal: Mix de folhas'),
      ('CHECKLIST ABERTURA — WRAP', 11, 'Verificar vegetal: Tomate cereja ao meio'),
      ('CHECKLIST ABERTURA — WRAP', 12, 'Verificar vegetal: Tomate rodela'),
      ('CHECKLIST ABERTURA — WRAP', 13, 'Verificar vegetal: Pepino fatiado'),
      ('CHECKLIST ABERTURA — WRAP', 14, 'Verificar pasta/creme: Guacamole'),
      ('CHECKLIST ABERTURA — WRAP', 15, 'Verificar pasta/creme: Hommus'),
      ('CHECKLIST ABERTURA — WRAP', 16, 'Verificar pasta/creme: Cream cheese'),
      ('CHECKLIST ABERTURA — WRAP', 17, 'Verificar pasta/creme: Creme de cogumelos'),
      ('CHECKLIST ABERTURA — WRAP', 18, 'Verificar pasta/creme: Creme de milho'),
      ('CHECKLIST ABERTURA — WRAP', 19, 'Verificar pasta/creme: Frijoles'),
      ('CHECKLIST ABERTURA — WRAP', 20, 'Verificar complemento: Azeitona preta fatiada'),
      ('CHECKLIST ABERTURA — WRAP', 21, 'Verificar complemento: Parmesão ralado'),
      ('CHECKLIST ABERTURA — WRAP', 22, 'Verificar complemento: Farofa de bacon'),
      ('CHECKLIST ABERTURA — WRAP', 23, 'Verificar complemento: Croutons'),
      ('CHECKLIST ABERTURA — WRAP', 24, 'Verificar complemento: Bacon laqueado'),
      ('CHECKLIST ABERTURA — WRAP', 25, 'Verificar complemento: Castanha de cajú'),
      ('CHECKLIST ABERTURA — WRAP', 26, 'Verificar complemento: Granola salgada'),
      ('CHECKLIST ABERTURA — WRAP', 27, 'Verificar complemento: Cheddar'),
      ('CHECKLIST ABERTURA — WRAP', 28, 'Verificar molho: Chimichurri'),
      ('CHECKLIST ABERTURA — WRAP', 29, 'Verificar molho: Molho Ranch'),
      ('CHECKLIST ABERTURA — WRAP', 30, 'Verificar molho: Molho Red Chili'),
      ('CHECKLIST ABERTURA — WRAP', 31, 'Verificar molho: Molho Mostarda e Mel'),
      ('CHECKLIST ABERTURA — WRAP', 32, 'Verificar molho: Molho Gorgonzola'),
      ('CHECKLIST ABERTURA — WRAP', 33, 'Verificar molho: Molho Barbecue'),
      ('CHECKLIST ABERTURA — WRAP', 34, 'Verificar molho: Molho Tahini'),
      ('CHECKLIST ABERTURA — WRAP', 35, 'Verificar molho: Azeite'),
      ('CHECKLIST ABERTURA — WRAP', 36, 'Verificar sal (saleiro abastecido)'),
      ('CHECKLIST ABERTURA — WRAP', 37, 'Conferir tortilhas/wraps disponíveis'),
      ('CHECKLIST ABERTURA — WRAP', 38, 'Verificar equipamento de aquecimento (se houver)'),
      ('CHECKLIST ABERTURA — WRAP', 39, 'Organizar estação de montagem'),
      ('CHECKLIST ABERTURA — SALADA', 1, 'Preparação pessoal completa'),
      ('CHECKLIST ABERTURA — SALADA', 2, 'Limpeza inicial da área'),
      ('CHECKLIST ABERTURA — SALADA', 3, 'Verificar vegetal grelhado: Abobrinha grelhada'),
      ('CHECKLIST ABERTURA — SALADA', 4, 'Verificar vegetal grelhado: Brócolis'),
      ('CHECKLIST ABERTURA — SALADA', 5, 'Verificar vegetal grelhado: Milho grelhado'),
      ('CHECKLIST ABERTURA — SALADA', 6, 'Verificar vegetal fresco: Pepino com cebola roxa'),
      ('CHECKLIST ABERTURA — SALADA', 7, 'Verificar vegetal fresco: Tomate cereja'),
      ('CHECKLIST ABERTURA — SALADA', 8, 'Verificar vegetal fresco: Picles de manga'),
      ('CHECKLIST ABERTURA — SALADA', 9, 'Verificar vegetal fresco: Picles de cenoura'),
      ('CHECKLIST ABERTURA — SALADA', 10, 'Verificar base: Fusili'),
      ('CHECKLIST ABERTURA — SALADA', 11, 'Verificar base: Quinoa'),
      ('CHECKLIST ABERTURA — SALADA', 12, 'Verificar base: Mix de folhas'),
      ('CHECKLIST ABERTURA — SALADA', 13, 'Verificar base: Alface romana baby'),
      ('CHECKLIST ABERTURA — SALADA', 14, 'Verificar proteína: Mussarela de búfala'),
      ('CHECKLIST ABERTURA — SALADA', 15, 'Verificar proteína: Parmesão'),
      ('CHECKLIST ABERTURA — SALADA', 16, 'Verificar proteína: Bacon laqueado'),
      ('CHECKLIST ABERTURA — SALADA', 17, 'Verificar proteína: Salmão desfiado'),
      ('CHECKLIST ABERTURA — SALADA', 18, 'Verificar complemento: Guacamole'),
      ('CHECKLIST ABERTURA — SALADA', 19, 'Verificar complemento: Azeitona'),
      ('CHECKLIST ABERTURA — SALADA', 20, 'Verificar complemento: Beer Flakes'),
      ('CHECKLIST ABERTURA — SALADA', 21, 'Verificar complemento: Croutons'),
      ('CHECKLIST ABERTURA — SALADA', 22, 'Verificar complemento: Granola salgada'),
      ('CHECKLIST ABERTURA — SALADA', 23, 'Verificar complemento: Nori'),
      ('CHECKLIST ABERTURA — SALADA', 24, 'Verificar complemento: Farofa vegana'),
      ('CHECKLIST ABERTURA — SALADA', 25, 'Verificar complemento: Gergelim torrado'),
      ('CHECKLIST ABERTURA — SALADA', 26, 'Verificar molho: Molho Mostarda e Mel'),
      ('CHECKLIST ABERTURA — SALADA', 27, 'Verificar molho: Molho Pesto'),
      ('CHECKLIST ABERTURA — SALADA', 28, 'Verificar molho: Molho Gorgonzola'),
      ('CHECKLIST ABERTURA — SALADA', 29, 'Verificar molho: Molho Ranch'),
      ('CHECKLIST ABERTURA — SALADA', 30, 'Verificar molho: Molho Itália'),
      ('CHECKLIST ABERTURA — SALADA', 31, 'Verificar bowls/embalagens para saladas'),
      ('CHECKLIST ABERTURA — SALADA', 32, 'Organizar estação de montagem'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 1, 'Uniforme completo (atenção à touca)'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 2, 'Limpeza da área de proteínas'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 3, 'Verificar proteína pronta: Apara de frango'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 4, 'Verificar proteína pronta: Frango defumado'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 5, 'Verificar proteína pronta: Carne da vovó'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 6, 'Verificar proteína pronta: Carne steak'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 7, 'Verificar proteína pronta: Frango crocante'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 8, 'Verificar proteína pronta: Frango italianinha'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 9, 'Verificar proteína pronta: Espeto de sobrecoxa'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 10, 'Verificar proteína pronta: Smash burger'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 11, 'Verificar proteína pronta: Falafel'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 12, 'Verificar proteína pronta: Ovos fritos'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 13, 'Verificar proteína pronta: Clara de ovos fritos'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 14, 'Verificar acompanhamento: Cebola caramelizada'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 15, 'Verificar molho: Molho da vovó'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 16, 'Verificar molho: Chimichurri'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 17, 'Verificar massa (se aplicável): Massa branca'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 18, 'Verificar massa (se aplicável): Massa amarela'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 19, 'Verificar massa (se aplicável): Massa preta'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 20, 'Verificar massa (se aplicável): Massa roxa'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 21, 'Verificar equipamentos (chapa, fritadeira)'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 22, 'Conferir estoque de proteínas para cocção'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 23, 'Verificar temperatura de geladeiras'),
      ('CHECKLIST ABERTURA — PROTEÍNA', 24, 'Organizar estação de finalização'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 1, 'Preparação pessoal completa'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 2, 'Limpar chapa completamente'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 3, 'Limpar fritadeira (por dentro e por fora)'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 4, 'Limpar mini freezer'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 5, 'Limpar superfícies de inox'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 6, 'Abastecer papeleira e saboneteira'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 7, 'Montar lixeiras específicas'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 8, 'Chapa - testar funcionamento'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 9, 'Fritadeira - testar aquecimento'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 10, 'Verificar termostatos'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 11, 'Verificar exaustão/coifa'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 12, 'Conferir etiquetas de validade'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 13, 'Organizar proteínas para cocção'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 14, 'Verificar estoque de batatas para fritar'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 15, 'Verificar óleo da fritadeira (nível e qualidade)'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 16, 'Preparar bandejas organizadas'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 17, 'Ligar chapa para pré-aquecimento'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 18, 'Ligar fritadeira (se necessário)'),
      ('CHECKLIST ABERTURA — CHAPA/FRITADEIRA', 19, 'Testar temperatura ideal'),
      ('CHECKLIST ABERTURA — DELIVERY', 1, 'Uniforme completo'),
      ('CHECKLIST ABERTURA — DELIVERY', 2, 'Limpar piso do delivery'),
      ('CHECKLIST ABERTURA — DELIVERY', 3, 'Limpar superfícies de inox'),
      ('CHECKLIST ABERTURA — DELIVERY', 4, 'Organizar área de embalagem'),
      ('CHECKLIST ABERTURA — DELIVERY', 5, 'Verificar seladora (ligar e testar)'),
      ('CHECKLIST ABERTURA — DELIVERY', 6, 'Verificar refrigeradores do delivery'),
      ('CHECKLIST ABERTURA — DELIVERY', 7, 'Preencher planilha de temperatura'),
      ('CHECKLIST ABERTURA — DELIVERY', 8, 'Verificar molhos embalados (Ranch, Mostarda e Mel, etc.)'),
      ('CHECKLIST ABERTURA — DELIVERY', 9, 'Verificar condimentos (Bear Flakes, farofas, cebola crispy)'),
      ('CHECKLIST ABERTURA — DELIVERY', 10, 'Verificar bebidas (sucos, refrigerantes, kombuchas)'),
      ('CHECKLIST ABERTURA — DELIVERY', 11, 'Verificar sobremesas (brownies)'),
      ('CHECKLIST ABERTURA — DELIVERY', 12, 'Verificar talheres, guardanapos, sacolas'),
      ('CHECKLIST ABERTURA — DELIVERY', 13, 'Verificar tablets/impressoras'),
      ('CHECKLIST ABERTURA — DELIVERY', 14, 'Testar conexão com apps (iFood, UberEats, etc.)'),
      ('CHECKLIST ABERTURA — DELIVERY', 15, 'Verificar estoque de embalagens'),
      ('CHECKLIST ABERTURA — DELIVERY', 16, 'Conferir lista de pedidos pendentes (se houver)'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 1, 'Preparação pessoal'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 2, 'Limpar máquina de café'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 3, 'Abastecer com água'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 4, 'Abastecer com grãos'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 5, 'Testar funcionamento'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 6, 'Fazer teste de extração'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 7, 'Verificar base: Morning Shot de tangerina'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 8, 'Verificar base: Supercoffee Choconilla'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 9, 'Verificar base: Whey de coco'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 10, 'Verificar base: Whey de baunilha'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 11, 'Verificar base: Whey de chocolate'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 12, 'Verificar frutas congeladas'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 13, 'Verificar líquidos (leites, iogurtes, água de coco)'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 14, 'Verificar complementos (canela, mel, pasta de amendoim)'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 15, 'Limpar liquidificadores'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 16, 'Organizar copos e canudos'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 17, 'Verificar gelo'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 18, 'Organizar estação de preparo'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 19, 'Verificar brownies'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 20, 'Verificar tortas/bombs'),
      ('CHECKLIST ABERTURA — BAR/SOBREMESA', 21, 'Organizar display'),
      ('CHECKLIST ABERTURA — LAVAGEM', 1, 'Uniforme completo (com avental impermeável)'),
      ('CHECKLIST ABERTURA — LAVAGEM', 2, 'Limpar pias e bancadas'),
      ('CHECKLIST ABERTURA — LAVAGEM', 3, 'Organizar prateleiras'),
      ('CHECKLIST ABERTURA — LAVAGEM', 4, 'Verificar produtos de limpeza'),
      ('CHECKLIST ABERTURA — LAVAGEM', 5, 'Abastecer sabão e desinfetante'),
      ('CHECKLIST ABERTURA — LAVAGEM', 6, 'Verificar abastecimento de produtos da máquina'),
      ('CHECKLIST ABERTURA — LAVAGEM', 7, 'Fazer lavagem inicial da máquina'),
      ('CHECKLIST ABERTURA — LAVAGEM', 8, 'Verificar temperatura da água'),
      ('CHECKLIST ABERTURA — LAVAGEM', 9, 'Testar ciclos de lavagem'),
      ('CHECKLIST ABERTURA — LAVAGEM', 10, 'Montar bandejas com jogo americano'),
      ('CHECKLIST ABERTURA — LAVAGEM', 11, 'Organizar cestos para talheres'),
      ('CHECKLIST ABERTURA — LAVAGEM', 12, 'Preparar área de pré-lavagem'),
      ('CHECKLIST ABERTURA — LAVAGEM', 13, 'Verificar estoque de luvas'),
      ('CHECKLIST ABERTURA — LAVAGEM', 14, 'Conferir caixas de utensílios das praças'),
      ('CHECKLIST ABERTURA — LAVAGEM', 15, 'Organizar por tipo (cubas, potes, talheres)'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 1, 'Limpar e desinfetar área do lixo'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 2, 'Organizar contêineres do lixo'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 3, 'Verificar vazamentos na área do lixo'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 4, 'Limpar e desinfetar bebedouro e pia de lavagem de mãos'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 5, 'Abastecer sabonete e papel (bebedouro/pia)'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 6, 'Varrer e passar pano úmido no salão'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 7, 'Limpar janelas/vidros do salão'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 8, 'Organizar tapetes externos (se aplicável)'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 9, 'Limpar sanitários dos banheiros clientes'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 10, 'Limpar pias e espelhos dos banheiros clientes'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 11, 'Abastecer papel, sabonete e toalhas (banheiros clientes)'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 12, 'Varrer calçada'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 13, 'Limpar mesas externas'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 14, 'Verificar lixeiras externas'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 15, 'Limpar e desinfetar banheiros funcionários'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 16, 'Abastecer insumos (banheiros funcionários)'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 17, 'Limpar mesas e bancadas do refeitório e corredor'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 18, 'Organizar armários do refeitório e corredor'),
      ('CHECKLIST ABERTURA — LIMPEZA GERAL', 19, 'Varrer e lavar piso do refeitório e corredor'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 1, 'Conferir presença de todos'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 2, 'Verificar uniformes'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 3, 'Verificar adornos retirados'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 4, 'Verificar toucas'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 5, 'Fazer plano de chão'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 6, 'Checar caixa e totens'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 7, 'Testar internet'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 8, 'Verificar menu boards'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 9, 'Verificar telas de senha'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 10, 'Testar sistema de impressão'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 11, 'Verificar todas as praças'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 12, 'Conferir validades'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 13, 'Verificar temperaturas'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 14, 'Verificar limpeza geral'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 15, 'Confirmar requisições'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 16, 'Ligar ar condicionado'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 17, 'Ligar som (playlist)'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 18, 'Ligar iluminação'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 19, 'Testar máquina de café'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 20, 'Posicionar equipe'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 21, 'Degustação amostral'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 22, 'Verificar apresentação'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 23, 'Confirmar estoques'),
      ('CHECKLIST ABERTURA — COORDENAÇÃO', 24, 'Liberar abertura')
  ) AS i(checklist_name, order_index, title)
)
INSERT INTO public.checklist_items (checklist_id, title, item_type, order_index, required)
SELECT c.id, i.title, 'check'::checklist_item_type, i.order_index, true
FROM inserted_checklists c
JOIN checklist_items i ON i.checklist_name = c.name
ORDER BY c.id, i.order_index;
